In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#dane


tabela_produktow = [f"Produkt{i+1}" for i in range(10)]
print(tabela_produktow)

# tabele zczytywac z excela c(wartociowosc od wagi od czegos dodatkowego np kalorie)
# ograniczenie plecaka tez (czy robic funkcje ktora wylicza ktore dni sa niehandlowe (niedziele i swieta))

['Produkt1', 'Produkt2', 'Produkt3', 'Produkt4', 'Produkt5', 'Produkt6', 'Produkt7', 'Produkt8', 'Produkt9', 'Produkt10']


In [ ]:
tabela_wartosciowosc_kalorie = np.random.randint(low=10, high=1000, size=10)
tabela_wartosciowosc_przydatnosc = np.random.randint(low=0, high=2, size=10)
tabela_wag = np.round(np.random.random(10) * 5, 2)

print(tabela_wartosciowosc_kalorie)
print(tabela_wartosciowosc_przydatnosc)
print(tabela_wag)




[567  68 325 260 657 979 436 675 534  72]
[1 1 1 1 0 0 0 0 0 0]
[0.17 1.27 1.66 2.14 4.66 0.32 2.42 0.93 4.08 2.63]


In [ ]:
tabela_merge = {}
for i in range(len(tabela_produktow)):
  tabela_merge[tabela_produktow[i]] = [tabela_wag[i], tabela_wartosciowosc_kalorie[i], tabela_wartosciowosc_przydatnosc[i]]

# print(tabela_merge)

df = pd.DataFrame(tabela_merge).transpose()
df.rename(columns={0: "waga", 1: "wartosciowosc", 2:"przydatnosc"})


waga  wartosciowosc  przydatnosc
Produkt1   0.17          567.0          1.0
Produkt2   1.27           68.0          1.0
Produkt3   1.66          325.0          1.0
Produkt4   2.14          260.0          1.0
Produkt5   4.66          657.0          0.0
Produkt6   0.32          979.0          0.0
Produkt7   2.42          436.0          0.0
Produkt8   0.93          675.0          0.0
Produkt9   4.08          534.0          0.0
Produkt10  2.63           72.0          0.0

In [ ]:
# Ograniczenia
x0 = 0 # poczatkowy stan lodowki
x_max = 10 # maksymalna ilosc produktow w lodowce w danym momencie
x_1 = 1 # maksymalna ilosc tego samego produktu
N = 365 #tbd
a_n = 20 # kg maksymalna pojemnosc_plecaka
b = 3000 # Zapotrzebowanie kaloryczne w danym dniu - w każdym dniu tyle samo





In [ ]:
import calendar
   
yy = 2017
   
# display the calendar
print(calendar.calendar(2018, 2, 1, 6))


                                  2018

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                1  2  3  4
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       5  6  7  8  9 10 11
15 16 17 18 19 20 21      12 13 14 15 16 17 18      12 13 14 15 16 17 18
22 23 24 25 26 27 28      19 20 21 22 23 24 25      19 20 21 22 23 24 25
29 30 31                  26 27 28                  26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1          1  2  3  4  5  6                   1  2  3
 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17
16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 22 23 24
23 24 25 26 27 28 29      28 


TODO  struktury danych:

xn - stan “lodówki” na początku x0 = 0

yn - decyzja czy w danym dniu idziemy na zakupy

n - n-ty dzień

an - ograniczenie pojemności plecaka w danym dniu

b - prędkość zużywania zapasów

ci - tabela wagi wartościowości

N - ilość dni do ustalenia terminarza


## Wątpliwosci

1) Czy dany produkt zużywamy w całości czy możemy zużyć tylko jego część
