# Modele - Implementacja <r>

- Barbara Pobiedzińska 400781
- Tomasz Brania 400642
- Marcin Biela 302959 <r>

Grupa 1a

In [18]:
import numpy as np
import pandas as pd


TODO  struktury danych:

xn - stan “lodówki” na początku x0 = 0

yn - decyzja czy w danym dniu idziemy na zakupy

n - n-ty dzień

an - ograniczenie pojemności plecaka w danym dniu

b - prędkość zużywania zapasów

ci - tabela wagi wartościowości

N - ilość dni do ustalenia terminarza


In [19]:
# Ograniczenia
x0 = 0 # poczatkowy stan lodowki
x_max = 10 # maksymalna ilosc produktow w lodowce w danym momencie
x_1 = 1 # maksymalna ilosc tego samego produktu
N = 365 #tbd
a_n = 20 # kg maksymalna pojemnosc_plecaka
b = 3000 # Zapotrzebowanie kaloryczne w danym dniu - w każdym dniu tyle samo
# Zakładamy, że w niedziele nie robimy zakupów

## dodane: mieisiac pierwszy
# lista_swiat = [(1, 1), (1, 6), (5, 1), (5, 3), (8, 15), (11, 1), (11, 11), (12, 25), (12, 26)]



In [20]:
#dane
n_records = 10

tabela_produktow = [f"Produkt{i+1}" for i in range(n_records)]
print(tabela_produktow)

# tabele zczytywac z excela c(wartociowosc od wagi od czegos dodatkowego np kalorie)
# ograniczenie plecaka tez (czy robic funkcje ktora wylicza ktore dni sa niehandlowe (niedziele i swieta))

['Produkt1', 'Produkt2', 'Produkt3', 'Produkt4', 'Produkt5', 'Produkt6', 'Produkt7', 'Produkt8', 'Produkt9', 'Produkt10']


In [21]:
tabela_wartosciowosc_kalorie = np.random.randint(low=10, high=1000, size=n_records)
tabela_wartosciowosc_przydatnosc = np.random.randint(low=0, high=2, size=n_records)
tabela_wag = np.round(np.random.random(n_records) * 5, 2)

print(tabela_wartosciowosc_kalorie)
print(tabela_wartosciowosc_przydatnosc)
print(tabela_wag)




[477 560 159 880 546  63 331 931 665 217]
[1 1 1 1 1 0 1 0 1 0]
[1.08 2.26 2.78 4.02 0.24 2.07 2.3  2.46 3.81 4.83]


In [22]:
tabela_merge = {}
for i in range(len(tabela_produktow)):
  tabela_merge[tabela_produktow[i]] = [tabela_wag[i], tabela_wartosciowosc_kalorie[i], tabela_wartosciowosc_przydatnosc[i]]

# print(tabela_merge)

df = pd.DataFrame(tabela_merge).transpose()
df.rename(columns={0: "waga", 1: "wartosciowosc", 2:"przydatnosc"})


waga  wartosciowosc  przydatnosc
Produkt1   1.08          477.0          1.0
Produkt2   2.26          560.0          1.0
Produkt3   2.78          159.0          1.0
Produkt4   4.02          880.0          1.0
Produkt5   0.24          546.0          1.0
Produkt6   2.07           63.0          0.0
Produkt7   2.30          331.0          1.0
Produkt8   2.46          931.0          0.0
Produkt9   3.81          665.0          1.0
Produkt10  4.83          217.0          0.0

In [23]:
# funkcja 
import calendar
import datetime

lista_swiat = [datetime.date(2022, 1, 1),
               datetime.date(2022, 1, 6),
               datetime.date(2022, 4, 17),
               datetime.date(2022, 4, 18), 
               datetime.date(2022, 5, 1),
               datetime.date(2022, 5, 3),
               datetime.date(2022, 6, 5),
               datetime.date(2022, 6, 16),
               datetime.date(2022, 7, 15),
               datetime.date(2022, 11, 1),
               datetime.date(2022, 11, 11),
               datetime.date(2022, 12, 25),
               datetime.date(2022, 12, 26)]


def returncalendar(first_day, first_month, first_year, last_day, last_month, last_year) :
  #doesnt include the last day -> update po dodaniu days = 1 tak
  #lista dni iteruje od 0
  
  # wielkanoc_mth = input("Kiedy Wielkanoc: numer miesiąca")
  # wielkanoc_day = input("Kiedy Wielkanoc: numer dnia")
  # boze_cialo_mth = input("Kiedy Boże Ciało: numer miesiąca")
  # boze_cialo_day = input("Kiedy Boże Ciało: numer dnia")

 # roboczo zeby nie wpisywac
  wielkanoc_mth = 4
  wielkanoc_day = 17
  boze_cialo_mth = 6
  boze_cialo_day = 16

  
  # lista_swiat_here = lista_swiat.copy()
  # lista_swiat_here.append((int(wielkanoc_mth), int(wielkanoc_day)))
  # lista_swiat_here.append((int(boze_cialo_mth), int(boze_cialo_day)))
  # # print(lista_swiat_here)

  # lista_swiat_here.sort()
  # # print(lista_swiat_here)


  vector_days = []

  d0 = datetime.date(first_year, first_month, first_day)
  d1 = datetime.date(last_year, last_month, last_day)

  start_date = d0
  end_date = d1
  delta = datetime.timedelta(days=1)

  while start_date <= end_date:
    weight = a_n
    if start_date.weekday() == 6:
      weight = 0
    
    if start_date in lista_swiat:
      weight = 0

    vector_days.append((start_date, start_date.weekday(), weight))
  
    start_date += delta

  return vector_days

  
vect = (returncalendar(1, 1, 2022, 15, 1, 2022))
for i in range(len(vect)):
  print(vect[i], '\n')



(datetime.date(2022, 1, 1), 5, 0) 

(datetime.date(2022, 1, 2), 6, 0) 

(datetime.date(2022, 1, 3), 0, 20) 

(datetime.date(2022, 1, 4), 1, 20) 

(datetime.date(2022, 1, 5), 2, 20) 

(datetime.date(2022, 1, 6), 3, 0) 

(datetime.date(2022, 1, 7), 4, 20) 

(datetime.date(2022, 1, 8), 5, 20) 

(datetime.date(2022, 1, 9), 6, 0) 

(datetime.date(2022, 1, 10), 0, 20) 

(datetime.date(2022, 1, 11), 1, 20) 

(datetime.date(2022, 1, 12), 2, 20) 

(datetime.date(2022, 1, 13), 3, 20) 

(datetime.date(2022, 1, 14), 4, 20) 

(datetime.date(2022, 1, 15), 5, 20) 



In [24]:

#### GARBAGE
  # obj = calendar.Calendar()
  # obj1 = calendar.TextCalendar()
  # print(obj1.formatmonth(year, month))

  # for day in obj.itermonthdays(year, month):
  #   print(day)

# year, month = 2017, 3
# obj = calendar.Calendar()
# obj1 = calendar.TextCalendar()
# print(obj1.formatmonth(year, month))

# for day in obj.itermonthdays(year, month):
#   print(day)

## Wątpliwosci

1) Czy dany produkt zużywamy w całości czy możemy zużyć tylko jego część
