# Modele - Implementacja </br>

- Barbara Pobiedzińska 400781
- Tomasz Brania 400642
- Marcin Biela 302959 </br>

Grupa 1a

In [78]:
import numpy as np
import pandas as pd
import random


TODO  struktury danych:

xn - stan “lodówki” na początku x0 = 0

yn - decyzja czy w danym dniu idziemy na zakupy

n - n-ty dzień

an - ograniczenie pojemności plecaka w danym dniu

b - prędkość zużywania zapasów

ci - tabela wagi wartościowości

N - ilość dni do ustalenia terminarza


In [79]:
# Ograniczenia
class lodowka():
  poczatkowy_stan_lodowki = 0 # poczatkowy stan lodowki
  
  maksymalna_poj_lodowki = 10 # maksymalna ilosc produktow w lodowce
  maks_liczba = 1 # maksymalna ilosc tego samego produktu
  N = 365 #tbd
  a_n = 7 # kg maksymalna pojemnosc_plecaka
  b = 3000 # Zapotrzebowanie kaloryczne w danym dniu - w każdym dniu tyle samo

  def __init__(self, terminarz, lista_produktow):
    self.terminarz = terminarz
    self.lista_produktow = lista_produktow
    self.initial_solution = self.generete_initial_solution()
    # self.aktualny_stan_lodowki = x0
    # self.aktualne_zapotrzebowanie_kaloryczne = b
  
  def generete_initial_solution(self) -> np.ndarray:
    initial_solution = []
    self.lista_produktow = self.lista_produktow.to_numpy()
    # print(self.lista_produktow)
    aktualny_stan_lodowki = self.poczatkowy_stan_lodowki
    zawartosc_lodowki = []
    for i in range(len(self.terminarz)):
      aktualny_stan_plecaka = 0
      if self.terminarz[i][2] != 0:
        teoretyczna_lista_zakupow = random.sample(range(10), 10)
        lista_1 = [0]*len(self.lista_produktow)
        count = 0
        while True:
            indeks_produktu_ktory_bierzemy = teoretyczna_lista_zakupow[count]
            waga_produktu = self.lista_produktow[indeks_produktu_ktory_bierzemy][0]

            if aktualny_stan_lodowki + 1 <= self.maksymalna_poj_lodowki and aktualny_stan_plecaka + waga_produktu <= self.a_n:
              lista_1[indeks_produktu_ktory_bierzemy] = 1
              zawartosc_lodowki.append(indeks_produktu_ktory_bierzemy)
              aktualny_stan_lodowki += 1
              aktualny_stan_plecaka += waga_produktu
              count += 1
            else:
              break
        initial_solution.append([1, lista_1 ])
      else:
        initial_solution.append([ 0, [] ]) 

      #zuzywanie produktow:
      aktualne_zuzycie = 0 #do self.b
      while aktualne_zuzycie < self.b:
        print(zawartosc_lodowki)
        jedzony_produkt = self.lista_produktow[zawartosc_lodowki.pop(0)]
        kalorycznosc = jedzony_produkt[1]
        aktualne_zuzycie += kalorycznosc
        aktualny_stan_lodowki -= 1

    # lista = np.random.randint(0, 10, 10)
    # for i in range(len(initial_solution)):
    #   if initial_solution[i][0] != 0:
    #     for j in range(len(self.lista_produktow)):
    #       initial_solution[i][1].append(np.random.randint(0, 2)) #ewentualnie mozna brac wiecej (randint (0, x))

    # dorzucic na kazdy dzien liste produktow , uwzgledniajac ich zuzycie -> czy spelnia to zapotrzebowanie
    return initial_solution

    def check_xmax(self):
      for i in range(len(initial_solution)):
        if initial_solution[i][1].count(1) <= self.maksymalna_poj_lodowki - self.aktualny_stan_lodowki:
          continue
        else:
          pass
# [p1, p2, p3, p4]
  # [1000, 1000, 2000, 500]
## [1, [1,1,0,1], 2500-3000=-500, [] ]
# piatek:
## [1, [0,0,1,1], ..., []]
# sobta:
# [0, [0,0,0,0]]
# poniedzialek
# [p1, p2, p3, p4]
  # [1000, 1000, 2000, 500]
  # [5, 5, 10, 7]
  # [1234] (kolejka)
## [1, [1,0,1,1], 4000-3000=----, [p4]]
# jezeli niedobór co do kalorycznosci
# jezeli nadmiar co do pojemnosci plecaka -> usuwamy najmniej kaloryczny produkt


# x0 = 0 # poczatkowy stan lodowki
# x_max = 10 # maksymalna ilosc produktow w lodowce w danym momencie
# x_1 = 1 # maksymalna ilosc tego samego produktu
# N = 365 #tbd
# a_n = 20 # kg maksymalna pojemnosc_plecaka
# b = 3000 # Zapotrzebowanie kaloryczne w danym dniu - w każdym dniu tyle samo
# # Zakładamy, że w niedziele nie robimy zakupów

## dodane: mieisiac pierwszy
# lista_swiat = [(1, 1), (1, 6), (5, 1), (5, 3), (8, 15), (11, 1), (11, 11), (12, 25), (12, 26)]

In [80]:
#dane
n_records = 10

tabela_produktow = [f"Produkt{i+1}" for i in range(n_records)]
print(tabela_produktow)

# tabele zczytywac z excela c(wartociowosc od wagi od czegos dodatkowego np kalorie)
# ograniczenie plecaka tez (czy robic funkcje ktora wylicza ktore dni sa niehandlowe (niedziele i swieta))

['Produkt1', 'Produkt2', 'Produkt3', 'Produkt4', 'Produkt5', 'Produkt6', 'Produkt7', 'Produkt8', 'Produkt9', 'Produkt10']


In [81]:
tabela_wartosciowosc_kalorie = np.random.randint(low=10, high=1000, size=n_records)
tabela_wartosciowosc_przydatnosc = np.random.randint(low=0, high=2, size=n_records)
tabela_wag = np.round(np.random.random(n_records) * 5, 2)

print(tabela_wartosciowosc_kalorie)
print(tabela_wartosciowosc_przydatnosc)
print(tabela_wag)




[396 706 729  45  98  56 532 128 369 594]
[0 0 1 1 1 0 1 1 1 1]
[2.83 0.93 2.92 2.71 4.24 1.91 2.   4.96 3.02 4.54]


In [82]:
tabela_merge = {}
for i in range(len(tabela_produktow)):
  tabela_merge[tabela_produktow[i]] = [tabela_wag[i], tabela_wartosciowosc_kalorie[i], tabela_wartosciowosc_przydatnosc[i]]

# print(tabela_merge)

df = pd.DataFrame(tabela_merge).transpose()
df.rename(columns={0: "waga", 1: "wartosciowosc", 2:"przydatnosc"})


waga  wartosciowosc  przydatnosc
Produkt1   2.83          396.0          0.0
Produkt2   0.93          706.0          0.0
Produkt3   2.92          729.0          1.0
Produkt4   2.71           45.0          1.0
Produkt5   4.24           98.0          1.0
Produkt6   1.91           56.0          0.0
Produkt7   2.00          532.0          1.0
Produkt8   4.96          128.0          1.0
Produkt9   3.02          369.0          1.0
Produkt10  4.54          594.0          1.0

In [83]:
df.to_numpy()

array([[  2.83, 396.  ,   0.  ],
       [  0.93, 706.  ,   0.  ],
       [  2.92, 729.  ,   1.  ],
       [  2.71,  45.  ,   1.  ],
       [  4.24,  98.  ,   1.  ],
       [  1.91,  56.  ,   0.  ],
       [  2.  , 532.  ,   1.  ],
       [  4.96, 128.  ,   1.  ],
       [  3.02, 369.  ,   1.  ],
       [  4.54, 594.  ,   1.  ]])

In [84]:
# funkcja 
import calendar
import datetime

lista_swiat = [datetime.date(2022, 1, 1),
               datetime.date(2022, 1, 6),
               datetime.date(2022, 4, 17),
               datetime.date(2022, 4, 18), 
               datetime.date(2022, 5, 1),
               datetime.date(2022, 5, 3),
               datetime.date(2022, 6, 5),
               datetime.date(2022, 6, 16),
               datetime.date(2022, 7, 15),
               datetime.date(2022, 11, 1),
               datetime.date(2022, 11, 11),
               datetime.date(2022, 12, 25),
               datetime.date(2022, 12, 26)]


def returncalendar(first_day, first_month, first_year, last_day, last_month, last_year) :
  #doesnt include the last day -> update po dodaniu days = 1 tak
  #lista dni iteruje od 0
  
  # wielkanoc_mth = input("Kiedy Wielkanoc: numer miesiąca")
  # wielkanoc_day = input("Kiedy Wielkanoc: numer dnia")
  # boze_cialo_mth = input("Kiedy Boże Ciało: numer miesiąca")
  # boze_cialo_day = input("Kiedy Boże Ciało: numer dnia")

 # roboczo zeby nie wpisywac
  wielkanoc_mth = 4
  wielkanoc_day = 17
  boze_cialo_mth = 6
  boze_cialo_day = 16

  
  # lista_swiat_here = lista_swiat.copy()
  # lista_swiat_here.append((int(wielkanoc_mth), int(wielkanoc_day)))
  # lista_swiat_here.append((int(boze_cialo_mth), int(boze_cialo_day)))
  # # print(lista_swiat_here)

  # lista_swiat_here.sort()
  # # print(lista_swiat_here)


  vector_days = []

  d0 = datetime.date(first_year, first_month, first_day)
  d1 = datetime.date(last_year, last_month, last_day)

  start_date = d0
  end_date = d1
  delta = datetime.timedelta(days=1)

  while start_date <= end_date:
    weight = lodowka.a_n
    if start_date.weekday() == 6:
      weight = 0
    
    if start_date in lista_swiat:
      weight = 0  # poj plecaka

    vector_days.append((start_date, start_date.weekday(), weight))
  
    start_date += delta

  return vector_days

  
terminarz = returncalendar(3, 1, 2022, 31, 1, 2022)
for i in range(len(terminarz)):
  print(terminarz[i], '\n')



(datetime.date(2022, 1, 3), 0, 7) 

(datetime.date(2022, 1, 4), 1, 7) 

(datetime.date(2022, 1, 5), 2, 7) 

(datetime.date(2022, 1, 6), 3, 0) 

(datetime.date(2022, 1, 7), 4, 7) 

(datetime.date(2022, 1, 8), 5, 7) 

(datetime.date(2022, 1, 9), 6, 0) 

(datetime.date(2022, 1, 10), 0, 7) 

(datetime.date(2022, 1, 11), 1, 7) 

(datetime.date(2022, 1, 12), 2, 7) 

(datetime.date(2022, 1, 13), 3, 7) 

(datetime.date(2022, 1, 14), 4, 7) 

(datetime.date(2022, 1, 15), 5, 7) 

(datetime.date(2022, 1, 16), 6, 0) 

(datetime.date(2022, 1, 17), 0, 7) 

(datetime.date(2022, 1, 18), 1, 7) 

(datetime.date(2022, 1, 19), 2, 7) 

(datetime.date(2022, 1, 20), 3, 7) 

(datetime.date(2022, 1, 21), 4, 7) 

(datetime.date(2022, 1, 22), 5, 7) 

(datetime.date(2022, 1, 23), 6, 0) 

(datetime.date(2022, 1, 24), 0, 7) 

(datetime.date(2022, 1, 25), 1, 7) 

(datetime.date(2022, 1, 26), 2, 7) 

(datetime.date(2022, 1, 27), 3, 7) 

(datetime.date(2022, 1, 28), 4, 7) 

(datetime.date(2022, 1, 29), 5, 7) 

(datetim

In [85]:
## easter
from dateutil.easter import *
from datetime import timedelta
year = 1994
print((easter(year)))
print((easter(year)+timedelta(60)))


1994-04-03
1994-06-02


In [86]:
# Tabu Search

# STEP 0

def check(initial_solution):
  pass



# def generate_initial_solution(terminarz, lista_produktow) -> np.ndarray:
#   initial_solution = []
#   lista_produktow = lista_produktow.to_numpy()
#   for i in range(len(terminarz)):
#     if terminarz[i][2] != 0:
#       initial_solution.append([ np.random.randint(0, 2), [] ])
#     else:
#       initial_solution.append([ 0, [] ]) 

#   for i in range(len(initial_solution)):
#     if initial_solution[i][0] != 0:
#       for j in range(len(lista_produktow)):
#         initial_solution[i][1].append(np.random.randint(0, 2)) #ewentualnie mozna brac wiecej (randint (0, x))
  
  
  
#   return initial_solution

# generate_initial_solution(terminarz, df)


In [87]:
l1 = lodowka(terminarz, df).initial_solution
for i in range(len(l1)):
  print(l1[i])

[4]
[]


IndexError: ignored

## Wątpliwosci

1) Czy dany produkt zużywamy w całości czy możemy zużyć tylko jego część


In [ ]:

#### GARBAGE
  # obj = calendar.Calendar()
  # obj1 = calendar.TextCalendar()
  # print(obj1.formatmonth(year, month))

  # for day in obj.itermonthdays(year, month):
  #   print(day)

# year, month = 2017, 3
# obj = calendar.Calendar()
# obj1 = calendar.TextCalendar()
# print(obj1.formatmonth(year, month))

# for day in obj.itermonthdays(year, month):
#   print(day)
# deck = list(range(0, 10))
# deck = list(range(1, 10001))
# random.shuffle(deck)
import random
random.sample(range(10), 10)